[package]
name = "adventofcode"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
arrayvec = "0.7"
hashbrown = "0.11"

[profile.release]
lto = true
panic = 'abort'
